# -*- coding: utf-8 -*-
"""first.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gQx5JIRTanGl9vlM1-itL9eRTgXH6pr0
"""

list=input("enter any values").split()
sum=0
for i in list:
  sum+=int(i)
print(sum)